@baseUrl = https://localhost:32769


// C1

POST {{baseUrl}}/api/chat/weather
Content-Type: application/json

[
  {
    "user": "What is the forcast for Mankato MN"
  }
]

### C1

POST {{baseUrl}}/api/chat/weather
Content-Type: application/json

[
  {
    "user": "string",
    "assistant": "string"
  }
]

