@baseUrl = https://localhost:32769


// C1

POST {{baseUrl}}/api/chat/weather
Content-Type: application/json

[
  {
    "user": "What is the forcast"
  }
]

### C1

POST {{baseUrl}}/api/chat/weather
Content-Type: application/json

[
  {
    "user": "What is the forcast for Mankato M",
    "assistant": "string"
  }
]

### Service Now

POST {{baseUrl}}/api/chat/servicenow
Content-Type: application/json

[
  {
    "user": "Are their any incidents impacting VPN?"
  }
]

### Auto

POST {{baseUrl}}/api/chat/rag/autoserviceadvisor
Content-Type: application/json

[
  {
    "user": "What type of oil do I need?"
  }
]