@baseUrl = https://localhost:32773


// C1

POST {{baseUrl}}/api/chat/weather
Content-Type: application/json

[
  {
    "user": "What is the forcast"
  }
]

### C1

POST {{baseUrl}}/api/chat/weather
Content-Type: application/json

[
  {
    "user": "What is the forcast for Mankato M",
    "assistant": "string"
  }
]

