name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    outputs:
      image-name: ${{ steps.image-name.outputs.IMAGE_NAME }}
      image-version: ${{ steps.image-name.outputs.IMAGE_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t assistants-hub .

      - name: Log in to ACR
        uses: docker/login-action@v1
        with:
          registry: rutzscolabcr.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Get the current date
        id: date
        run: echo "::set-output name=tag::$(date +'%Y%m%d%H%M%S')"
        
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rutzscolabcr.azurecr.io/custom-chat-copilot/assistants-hub:${{ steps.date.outputs.tag }}

      - name: Set image name for other jobs
        id: image-name
        run: |
          echo "IMAGE_VERSION=${{ steps.date.outputs.tag }}" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=rutzscolabcr.azurecr.io/custom-chat-copilot/assistants-hub" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ needs.build.outputs.image-name }}
      IMAGE_VERSION: ${{ needs.build.outputs.image-version }}
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ECHO VARIABLES
        run: |
          echo "IMAGE_NAME = $IMAGE_NAME"
          echo "IMAGE_VERSION = $IMAGE_VERSION"